"""
Streamlit web interface for the Bedtime Story Generator.

Run with:
    streamlit run app.py
"""

import html
import streamlit as st
from graph import run_pipeline
from utils import StoryConfig

# ── Page config ────────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="Bedtime Story Generator",
    page_icon="🌙",
    layout="centered",
)

# ── Custom CSS ─────────────────────────────────────────────────────────────────

st.markdown("""
<style>
  /* Background and font */
  .stApp {
    background-color: #1a1035;
    color: #f0e6d3;
  }

  /* Main heading */
  h1 {
    color: #f7c948 !important;
    font-family: Georgia, serif;
    text-align: center;
    font-size: 2.4rem !important;
    letter-spacing: 0.04em;
  }

  /* Sub-heading */
  h3 {
    color: #d4a96a !important;
    font-family: Georgia, serif;
  }

  /* Story card */
  .story-card {
    background-color: #2a1f50;
    border-radius: 16px;
    padding: 2rem 2.5rem;
    font-family: Georgia, serif;
    font-size: 1.1rem;
    line-height: 1.9;
    color: #f0e6d3;
    white-space: pre-wrap;
    border: 1px solid #3d2e6b;
  }

  /* Story title inside card */
  .story-title {
    font-size: 1.45rem;
    font-weight: bold;
    color: #f7c948;
    text-align: center;
    margin-bottom: 1.2rem;
    font-family: Georgia, serif;
  }

  /* Score bar label */
  .score-label {
    font-size: 0.9rem;
    color: #c9b8e8;
    margin-bottom: 2px;
  }

  /* Info badge row */
  .badge-row {
    display: flex;
    gap: 12px;
    flex-wrap: wrap;
    margin-bottom: 1rem;
  }
  .badge {
    background: #3d2e6b;
    border-radius: 20px;
    padding: 4px 14px;
    font-size: 0.85rem;
    color: #d4a96a;
    border: 1px solid #5a4899;
  }

  /* Section divider */
  hr {
    border-color: #3d2e6b;
  }

  /* Input label */
  label {
    color: #d4a96a !important;
    font-size: 1rem;
  }

  /* Text area */
  textarea {
    background-color: #2a1f50 !important;
    color: #f0e6d3 !important;
    border-color: #5a4899 !important;
    border-radius: 10px !important;
  }

  /* Buttons */
  .stButton > button {
    background-color: #f7c948;
    color: #1a1035;
    font-weight: bold;
    font-size: 1rem;
    border-radius: 10px;
    border: none;
    padding: 0.55rem 2rem;
  }
  .stButton > button:hover {
    background-color: #ffe080;
    color: #1a1035;
  }
</style>
""", unsafe_allow_html=True)

# ── Header ─────────────────────────────────────────────────────────────────────

st.markdown("# 🌙 Bedtime Story Generator")
st.markdown(
    "<p style='text-align:center;color:#9b89c4;font-size:1rem;'>"
    "Age-appropriate stories for children 5–10, generated by a multi-agent AI pipeline."
    "</p>",
    unsafe_allow_html=True,
)
st.markdown("---")

# ── Input form ─────────────────────────────────────────────────────────────────

prompt = st.text_area(
    "What kind of story would you like?",
    placeholder="e.g. A story about a brave girl who is scared of the dark but has to save her little brother.",
    height=100,
)

col1, col2, col3 = st.columns([1, 2, 1])
with col2:
    generate = st.button("✨ Generate Story", use_container_width=True)

# ── Pipeline execution ─────────────────────────────────────────────────────────

if generate:
    if not prompt.strip():
        st.warning("Please enter a story prompt first.")
    else:
        with st.spinner("Writing your story… this takes about 20–40 seconds."):
            cfg = StoryConfig()
            try:
                state = run_pipeline(prompt.strip(), cfg)
            except EnvironmentError:
                st.error(
                    "**OPENAI_API_KEY not set.**  \n"
                    "Start the app with your key exported:  \n"
                    "`OPENAI_API_KEY=your-key streamlit run app.py`"
                )
                st.stop()

        st.markdown("---")

        # ── Story display ──────────────────────────────────────────────────────

        story = state.get("final_story") or state.get("story", "")
        plan = state.get("plan", {})
        evaluation = state.get("evaluation", {})
        classification = state.get("classification", {})

        title = plan.get("title", "Your Story")

        st.markdown(
            f"<div class='story-card'>"
            f"<div class='story-title'>{html.escape(title)}</div>"
            f"{html.escape(story)}"
            f"</div>",
            unsafe_allow_html=True,
        )

        st.markdown("---")

        # ── Metadata badges ────────────────────────────────────────────────────

        genre = classification.get("genre", "—").capitalize()
        tone = classification.get("tone", "—").capitalize()
        age_target = plan.get("estimated_age_target", "—")
        word_count = len(story.split())
        iterations = state.get("iteration_count", 1)
        fk_grade = evaluation.get("reading_level_grade", "—")

        badges_html = (
            "<div class='badge-row'>"
            f"<span class='badge'>📖 Genre: {genre}</span>"
            f"<span class='badge'>🎭 Tone: {tone}</span>"
            f"<span class='badge'>👧 Age: {age_target}+</span>"
            f"<span class='badge'>📝 Words: {word_count}</span>"
            f"<span class='badge'>🔄 Refinements: {max(0, iterations - 1)}</span>"
            f"<span class='badge'>🎓 Reading level: Grade {fk_grade}</span>"
            "</div>"
        )
        st.markdown(badges_html, unsafe_allow_html=True)

        # ── Scorecard ──────────────────────────────────────────────────────────

        st.markdown("### 📊 Quality Scorecard")

        overall = evaluation.get("overall", 0)
        overall_color = "#4caf50" if overall >= 8.0 else "#ff9800" if overall >= 7.0 else "#f44336"
        st.markdown(
            f"<p style='font-size:1.4rem;font-weight:bold;color:{overall_color};'>"
            f"Overall score: {overall:.2f} / 10"
            f"</p>",
            unsafe_allow_html=True,
        )

        dim_labels = {
            "content_safety": "Content Safety (25%)",
            "vocabulary_accessibility": "Vocabulary Accessibility (20%)",
            "coherence": "Coherence (20%)",
            "narrative_arc": "Narrative Arc (20%)",
            "engagement": "Engagement (15%)",
        }
        dim_scores = evaluation.get("scores", {})

        for key, label in dim_labels.items():
            score = dim_scores.get(key, 0)
            st.markdown(f"<div class='score-label'>{label}</div>", unsafe_allow_html=True)
            st.progress(score / 10.0, text=f"{score:.1f} / 10")

        # ── Critique (collapsed) ───────────────────────────────────────────────

        critique = evaluation.get("critique", "")
        if critique:
            with st.expander("Judge's notes"):
                st.markdown(
                    f"<p style='color:#c9b8e8;font-size:0.9rem;'>{critique}</p>",
                    unsafe_allow_html=True,
                )

        # ── Download ───────────────────────────────────────────────────────────

        st.markdown("---")
        st.download_button(
            label="⬇️ Download story as .txt",
            data=f"{title}\n\n{story}",
            file_name=f"{title.lower().replace(' ', '_')}.txt",
            mime="text/plain",
        )
